import PrivacyControls from "./PrivacyControls";

export default function PrivacyPage() {
  const controller = process.env.PRIVACY_CONTROLLER_NAME ?? "[Completează numele operatorului]";
  const contactEmail = process.env.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL ?? "[Completează e-mailul pentru solicitări de confidențialitate]";

  return <main className="min-h-screen bg-[#f6f3ee] px-6 py-10 text-[#173f35]"><div className="mx-auto max-w-4xl"><a href="/feed" className="mb-6 inline-block text-sm text-slate-500 hover:text-[#173f35]">← Înapoi la Acasă</a><header className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#d66c4f]">Roommate</p><h1 className="mt-2 text-3xl font-semibold">Confidențialitate și datele tale</h1><p className="mt-2 text-sm text-slate-500">Informare actualizată la 5 octombrie 2026 · Proiect demonstrativ, necesită completarea detaliilor operatorului înainte de lansare.</p></header>
    <div className="mb-6 space-y-5 rounded-3xl bg-white p-6 text-sm leading-6 text-slate-600 shadow-lg shadow-[#173f35]/5 sm:p-8">
      <section><h2 className="font-semibold text-[#173f35]">Cine răspunde de date</h2><p className="mt-2">Operator: <strong>{controller}</strong>. Contact pentru întrebări și solicitări privind datele: {contactEmail.includes("@") ? <a className="font-semibold text-[#a8472f] underline" href={`mailto:${contactEmail}`}>{contactEmail}</a> : <strong>{contactEmail}</strong>}. Completează identitatea legală și datele de contact înainte de utilizarea publică.</p></section>
      <section><h2 className="font-semibold text-[#173f35]">Ce date prelucrăm și de ce</h2><ul className="mt-2 list-disc space-y-1 pl-5"><li>Date de cont (e-mail și identificator Supabase) pentru autentificare și funcționarea contului.</li><li>Profilul și preferințele de locuire pentru recomandări și calcularea scorului de compatibilitate.</li><li>Mesaje directe, postări, match-uri, blocări, raportări și date de grup pentru funcțiile solicitate de utilizatori și siguranța serviciului.</li><li>Data nașterii și genul furnizate în profil. CNP-ul este opțional: dacă este completat, este validat în browser și folosit pentru a calcula aceste câmpuri.</li><li>Pentru căutarea opțională după CNP în invitațiile Groupchat se păstrează un HMAC cu cheie de server, nu CNP-ul în clar. Dezactivarea opțiunii șterge HMAC-ul și istoricul recent al căutărilor.</li></ul><p className="mt-2">Scorul de compatibilitate ordonează recomandările; nu produce o decizie cu efect juridic sau similar semnificativ.</p></section>
      <section><h2 className="font-semibold text-[#173f35]">Destinatari și stocare</h2><p className="mt-2">Datele sunt stocate în proiectul Supabase configurat de operator și procesate de furnizorii de hosting și infrastructură configurați pentru aplicație. Profilurile pot fi afișate utilizatorilor autentificați, iar conturile staff pot vedea match-uri confirmate și profilurile aferente. Operatorul trebuie să completeze furnizorii, locațiile de stocare, transferurile internaționale aplicabile și perioadele de retenție, inclusiv pentru backup-uri și loguri.</p></section>
      <section><h2 className="font-semibold text-[#173f35]">Drepturile tale</h2><p className="mt-2">Poți cere acces, rectificare, ștergere, restricționare sau portabilitatea datelor și te poți opune prelucrării atunci când se aplică. Editează profilul pentru rectificări, dezactivează căutarea CNP din profil sau folosește exportul și ștergerea de mai jos. Pentru alte solicitări, scrie la adresa de contact; în mod obișnuit, răspunsul la o solicitare de drepturi este datorat în cel mult o lună. Poți depune o plângere la <a className="font-semibold text-[#a8472f] underline" href="https://www.dataprotection.ro/index.jsp?lang=ro&page=procedura_plangerilor" target="_blank" rel="noreferrer">ANSPDCP</a>.</p></section>
      <section><h2 className="font-semibold text-[#173f35]">Baza legală și retenția</h2><p className="mt-2">Operatorul trebuie să documenteze temeiul juridic pentru fiecare scop, perioada de retenție, procedura pentru solicitări și contractele cu furnizorii înainte de lansarea publică. În special, folosirea unui număr național de identificare precum CNP necesită evaluare separată a temeiului și garanțiilor aplicabile în România. Această pagină este o informare tehnică de proiect, nu o confirmare de conformitate juridică.</p></section>
    </div>
    <PrivacyControls />
  </div></main>;
}
